services:
  backend:
    volumes:
      - ./backend:/app  # Mount local backend code
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/interview

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev  # Explicitly use the dev stage
    ports:
      - "5173:5173"  # Vite's default dev server port
    volumes:
      - ./frontend:/app  # Mount local frontend code
      - /app/node_modules/ # Exclude node_modules from being mounted
    command: vite --host 0.0.0.0  # Run development server

  # loki:
  #   command: -config.file=/etc/loki/config.yaml

  postgres:
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
