"""adding user selected position to the user settings

Revision ID: 83a9325651ab
Revises: 38c04562a334
Create Date: 2024-12-15 13:47:00.122859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '83a9325651ab'
down_revision: Union[str, None] = '38c04562a334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('positions', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('user_settings', sa.Column('selected_position_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'selected_position_id')
    op.alter_column('positions', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
